set_property IOSTANDARD LVCMOS33 [get_ports {AN[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AL[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AL[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AL[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AL[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {H_in0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {H_in0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {H_in0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {H_in0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {H_in1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {H_in1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_in0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_in0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_in0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_in0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_in1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_in1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_in1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M_in1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports AL_ON]
set_property IOSTANDARD LVCMOS33 [get_ports LD_alarm]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports AUD_PWM]
set_property IOSTANDARD LVCMOS33 [get_ports AUD_SD]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports resett]
set_property IOSTANDARD LVCMOS33 [get_ports snooze]
set_property IOSTANDARD LVCMOS33 [get_ports STOP_al]


set_property PACKAGE_PIN A11 [get_ports AUD_PWM]
set_property PACKAGE_PIN D12 [get_ports AUD_SD]
set_property PACKAGE_PIN V10 [get_ports AL_ON]
set_property PACKAGE_PIN N17 [get_ports reset]
set_property PACKAGE_PIN P17 [get_ports resett]
set_property PACKAGE_PIN M17 [get_ports STOP_al]
set_property PACKAGE_PIN M18 [get_ports snooze]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN U11 [get_ports LD_alarm]
set_property PACKAGE_PIN U13 [get_ports {AN[7]}]
set_property PACKAGE_PIN K2 [get_ports {AN[6]}]
set_property PACKAGE_PIN T14 [get_ports {AN[5]}]
set_property PACKAGE_PIN P14 [get_ports {AN[4]}]
set_property PACKAGE_PIN J14 [get_ports {AN[3]}]
set_property PACKAGE_PIN T9 [get_ports {AN[2]}]
set_property PACKAGE_PIN J18 [get_ports {AN[1]}]
set_property PACKAGE_PIN J17 [get_ports {AN[0]}]
set_property PACKAGE_PIN N15 [get_ports {AL[5]}]
set_property PACKAGE_PIN M16 [get_ports {AL[4]}]
set_property PACKAGE_PIN R12 [get_ports {AL[3]}]
set_property PACKAGE_PIN G14 [get_ports {AL[2]}]
set_property PACKAGE_PIN R11 [get_ports {AL[1]}]
set_property PACKAGE_PIN N16 [get_ports {AL[0]}]
set_property PACKAGE_PIN T10 [get_ports {seg[6]}]
set_property PACKAGE_PIN R10 [get_ports {seg[5]}]
set_property PACKAGE_PIN K16 [get_ports {seg[4]}]
set_property PACKAGE_PIN K13 [get_ports {seg[3]}]
set_property PACKAGE_PIN P15 [get_ports {seg[2]}]
set_property PACKAGE_PIN T11 [get_ports {seg[1]}]
set_property PACKAGE_PIN L18 [get_ports {seg[0]}]
set_property PACKAGE_PIN J15 [get_ports {M_in0[0]}]
set_property PACKAGE_PIN L16 [get_ports {M_in0[1]}]
set_property PACKAGE_PIN M13 [get_ports {M_in0[2]}]
set_property PACKAGE_PIN R15 [get_ports {M_in0[3]}]
set_property PACKAGE_PIN R17 [get_ports {M_in1[0]}]
set_property PACKAGE_PIN T18 [get_ports {M_in1[1]}]
set_property PACKAGE_PIN U18 [get_ports {M_in1[2]}]
set_property PACKAGE_PIN R13 [get_ports {M_in1[3]}]
set_property PACKAGE_PIN T8 [get_ports {H_in0[0]}]
set_property PACKAGE_PIN U8 [get_ports {H_in0[1]}]
set_property PACKAGE_PIN R16 [get_ports {H_in0[2]}]
set_property PACKAGE_PIN T13 [get_ports {H_in0[3]}]
set_property PACKAGE_PIN H6 [get_ports {H_in1[0]}]
set_property PACKAGE_PIN U12 [get_ports {H_in1[1]}]


set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { led[0] }]; #IO_L18P_T2_A24_15 Sch=led[0]
set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { led[1] }]; #IO_L24P_T3_RS1_15 Sch=led[1]
set_property -dict { PACKAGE_PIN J13   IOSTANDARD LVCMOS33 } [get_ports { led[2] }]; #IO_L17N_T2_A25_15 Sch=led[2]
set_property -dict { PACKAGE_PIN N14   IOSTANDARD LVCMOS33 } [get_ports { led[3] }]; #IO_L8P_T1_D11_14 Sch=led[3]
set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports { led[4] }]; #IO_L7P_T1_D09_14 Sch=led[4]
set_property -dict { PACKAGE_PIN V17   IOSTANDARD LVCMOS33 } [get_ports { led[5] }]; #IO_L18N_T2_A11_D27_14 Sch=led[5]
set_property -dict { PACKAGE_PIN U17   IOSTANDARD LVCMOS33 } [get_ports { led[6] }]; #IO_L17P_T2_A14_D30_14 Sch=led[6]
set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 } [get_ports { led[7] }]; #IO_L18P_T2_A12_D28_14 Sch=led[7]



set_property -dict { PACKAGE_PIN C14   IOSTANDARD LVCMOS33 } [get_ports { SCL }]; #IO_L1N_T0_AD0N_15 Sch=tmp_scl
set_property -dict { PACKAGE_PIN C15   IOSTANDARD LVCMOS33 } [get_ports { SDA }]; #IO_L12N_T1_MRCC_15 Sch=tmp_sda


